Epoch:   0%|                                                                                                                    | 0/150 [00:00<?, ?it/s]2025-03-24 15:53:30.467:INFO:__main__ - [Epoch 1]
Training Iteration:   0%|                                                                                                       | 0/113 [00:01<?, ?it/s]
Epoch:   0%|                                                                                                                    | 0/150 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "FlashVTG_ms/train.py", line 452, in <module>
    best_ckpt_path, eval_split_name, eval_path, debug, opt = start_training()
  File "FlashVTG_ms/train.py", line 423, in start_training
    train(model, criterion, optimizer, lr_scheduler, train_dataset, eval_dataset, opt)
  File "FlashVTG_ms/train.py", line 140, in train
    model, criterion, train_loader, optimizer, opt, epoch_i, tb_writer
  File "FlashVTG_ms/train.py", line 58, in train_epoch
    loss_dict = criterion(batch, outputs, targets)
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/SSD1/minseok/MR_HD/FlashVTG/FlashVTG_ms/model.py", line 685, in forward
    losses.update(self.get_loss(loss, outputs, targets))
  File "/SSD1/minseok/MR_HD/FlashVTG/FlashVTG_ms/model.py", line 653, in get_loss
    return loss_map[loss](outputs, targets, **kwargs)
  File "/SSD1/minseok/MR_HD/FlashVTG/FlashVTG_ms/model.py", line 359, in loss_saliency
    loss_neg_pair = (- torch.log(1. - torch.sigmoid(saliency_scores_neg)) * (vid_token_mask[real_neg_mask])).sum(dim=1).mean()
RuntimeError: The size of tensor a (116) must match the size of tensor b (75) at non-singleton dimension 1
