Epoch:   0%|                                                                                                                    | 0/150 [00:00<?, ?it/s]2025-03-24 15:51:37.421:INFO:__main__ - [Epoch 1]
Training Iteration:   0%|                                                                                                       | 0/113 [00:01<?, ?it/s]
Epoch:   0%|                                                                                                                    | 0/150 [00:01<?, ?it/s]
output torch.Size([116, 64, 256])
output torch.Size([116, 64, 256])
Traceback (most recent call last):
  File "FlashVTG_ms/train.py", line 452, in <module>
    best_ckpt_path, eval_split_name, eval_path, debug, opt = start_training()
  File "FlashVTG_ms/train.py", line 423, in start_training
    train(model, criterion, optimizer, lr_scheduler, train_dataset, eval_dataset, opt)
  File "FlashVTG_ms/train.py", line 140, in train
    model, criterion, train_loader, optimizer, opt, epoch_i, tb_writer
  File "FlashVTG_ms/train.py", line 58, in train_epoch
    loss_dict = criterion(batch, outputs, targets)
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/SSD1/minseok/MR_HD/FlashVTG/FlashVTG_ms/model.py", line 680, in forward
    losses = self.loss(new_outputs, outputs)
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/SSD1/minseok/MR_HD/FlashVTG/blocks/loss.py", line 175, in forward
    output = self.loss_cls(data, output, cls_tgt)
  File "/SSD1/minseok/MR_HD/FlashVTG/blocks/loss.py", line 141, in loss_cls
    loss_cls = self._loss_cls(src, cls_tgt, weight=msk, avg_factor=msk.sum())
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/nncore/nn/losses/focal.py", line 147, in forward
    avg_factor=avg_factor) * self._loss_weight
  File "/home/mvpserver20/anaconda3/envs/cgdetr/lib/python3.7/site-packages/nncore/nn/losses/utils.py", line 22, in _wrapper
    loss = loss * weight
RuntimeError: The size of tensor a (217) must match the size of tensor b (139) at non-singleton dimension 1
